heightTexture = "height.png"
map = "dtrdtf2.txt"
ground = "backg3.png"
mapGround = "ground1.png"
mapGroundNormal = ""
genOffset = "75"
xCurvature = "15"
xCurvatureSmoothness = "3"
heightMapTiling = "1"
heightMapSpeed = "0"
heightMapMaxHeight = "5"
heightMapSamplingWidth = "8"
xMoveTiling = "100"
fogColor = {["Red"] = "0.1058824" , ["Green"] = "0.5803922" , ["Blue"] = "0.8901961"}
lightParameter = "mappack1Light.lua"