heightTexture = "height.png"
map = "dtrdtf3.txt"
ground = "backg3.png"
mapGround = "ground5.png"
mapGroundNormal = ""
genOffset = "75"
xCurvature = "15"
xCurvatureSmoothness = "3"
heightMapTiling = "1"
heightMapSpeed = "0"
heightMapMaxHeight = "5"
heightMapSamplingWidth = "8"
xMoveTiling = "100"
fogColor = {["Red"] = "0.8117647" , ["Green"] = "0.1843137" , ["Blue"] = "0.2039216"}
lightParameter = "mappack1Light.lua"