heightTexture = "height.png"
map = "map1.txt"
ground = "backg3.png"
mapGround = "ground1.png"
mapGroundNormal = ""
genOffset = "75"
xCurvature = "15"
xCurvatureSmoothness = "3"
heightMapTiling = "1"
heightMapSpeed = "0"
heightMapMaxHeight = "5"
heightMapSamplingWidth = "8"
xMoveTiling = "100"
lightParameter = "map1Light.lua"
fogColor = {["Red"] = "1" , ["Green"] = "0.2901961" , ["Blue"] = "0"}
