heightMapSamplingWidth = "8"
map = "map3.txt"
ground = "backg3.png"
mapGround = "ground2.png"
mapGroundNormal = ""
genOffset = "75"
xCurvature = "15"
xCurvatureSmoothness = "3"
heightMapTiling = "1"
heightMapSpeed = "0"
heightMapMaxHeight = "5"
xMoveTiling = "100"
fogColor = {["Red"] = "0.5" , ["Green"] = "0.5" , ["Blue"] = "0.5"}
lightParameter = "map1Light.lua"
