heightTexture = "ground5.png"
map = "SecondMap_Village.txt"
ground = "backg.png"
mapGround = "ground3.png"
mapGroundNormal = ""
genOffset = "75"
xCurvature = "25"
xCurvatureSmoothness = "3"
heightMapTiling = "1"
heightMapSpeed = "0"
heightMapMaxHeight = "5"
heightMapSamplingWidth = "8"
xMoveTiling = "100"
fogColor = {["Red"] = "0.1215686" , ["Green"] = "0.2941177" , ["Blue"] = "0.3176471"}
