heightTexture = "height.png"
map = "temp.txt"
ground = "backg3.png"
mapGround = "ground3.png"
mapGroundNormal = ""
genOffset = "75"
xCurvature = "15"
xCurvatureSmoothness = "3"
heightMapTiling = "1"
heightMapSpeed = "0"
heightMapMaxHeight = "5"
heightMapSamplingWidth = "8"
xMoveTiling = "100"
fogColor = {["Red"] = "0.5" , ["Green"] = "0.5" , ["Blue"] = "0.5"}
