heightTexture = "height.png"
map = "temp.txt"
ground = "backg3.png"
mapGround = "ground2.png"
mapGroundNormal = ""
genOffset = "75"
xCurvature = "50"
xCurvatureSmoothness = "2"
heightMapTiling = "1"
heightMapSpeed = "0"
heightMapMaxHeight = "10"
heightMapSamplingWidth = "8"
xMoveTiling = "100"
fogColor = {["Red"] = "0.5" , ["Green"] = "0.5" , ["Blue"] = "0.5"}
